server:
  port: 7072
beetl:
  templatesPath: /views

spring:
  application:
    name: iot-alram
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.addr}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${mysql.username}
    password: ${mysql.password}
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update

mysql:
    addr:  59.110.152.131
    port: 3306
    database: wb
    username: root
    password: 1234
