server:
  port: 7072
beetl:
  templatesPath: /views
entitymanager:
    packagesToScan: com.lxr.ab.domain
spring:
  application:
    name: wb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.addr}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${mysql.username}
    password: ${mysql.password}
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: true
      open-in-view: false
      properties:
          hibernate.id.new_generator_mappings: true
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: true
          hibernate.hbm2ddl.auto: update
          hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

mysql:
    addr:  59.110.152.131
    port: 3306
    database: wb
    username: root
    password: 1234

#mysql:
#    addr:  192.168.0.50
#    port: 3309
#    database: crong_db
#    username: root
#    password: Crong123!
